config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'chats#new'
  resources :chats, only: %i[new create show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  validates :text, presence: true
end

app/models/open_ai.rb
# frozen_string_literal: true

# OpenAI APIを叩く
class OpenAi
  require 'ruby/openai'

  def self.generate(text)
    client = OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY']) # API keyを記述
    response = client.chat(
      parameters: {
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'user',
                     # contentにプロンプトの詳細を記述。
                     content: "「材料は#{text}」です。レシピを作成してください" }]
      }
    )
    response.dig('choices', 0, 'message', 'content')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def show
    @chat = Chat.find(params[:id])
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      response_message = OpenAi.generate(@chat.text)
      @chat.update(response_message: response_message)
      redirect_to @chat
    else
      render :new
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:text)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/views/chats/new.html.erb
<div class="center-form">
  <h1>食材からレシピ作成アプリ</h1>
  <h3>フォームに材料を入力してください</h3>
  <%= form_with model: @chat, url: chats_path, method: :post do |form| %>
    <%= form.text_field :text %>
    <%= form.submit "送信" %>
  <% end %>
</div>

app/views/chats/show.html.erb
<div class="response-container">
  <h1>レシピ名</h1>
  <div class="response-box">
    <%= simple_format(@chat.response_message) %>
  </div>
  <div>
    <%= link_to '材料から検索する', new_chat_path, class: "button-style" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestChatgpt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>